#!/bin/bash
# Does not run if your local branch is behind the remote.
# https://gist.github.com/stefansundin/82051ad2c8565999b914

# Exit early if this was only a file checkout, not a branch change ($3 == 1)
[[ $3 == 0 ]] && exit 0

oldRef=$1
newRef=$2

# Exit early if the local branch is behind the remote
LOCAL=$(git rev-parse @)
REMOTE=$(git rev-parse @{u} 2> /dev/null)
BASE=$(git merge-base @ @{u} 2> /dev/null)

if [[ "$LOCAL" != "$REMOTE" && "$LOCAL" = "$BASE" ]]; then
  echo "You are behind origin, not running bundle/migrate post-checkout hook."
  exit 1
fi


function changed {
  git diff --name-only $oldRef $newRef | grep "^$1" > /dev/null 2>&1
}

if changed 'bower.json'; then
  echo "bower.json changed, installing"
  bower prune
  bower install
fi

if changed 'package.json'; then
  echo "Package.json changed, installing"
  npm prune
  npm install
fi
